import React, { useState } from 'react';
import {
  Download,
  Sliders,
  CheckCircle2,
  Copy,
  TrendingUp,
  Percent,
  FileCheck,
  ChevronDown,
  Sparkles,
  AlertCircle,
  RefreshCw
} from 'lucide-react';
import { ScoreGauge } from '../ScoreGauge';
import { DiffCard } from '../DiffCard';
import { BorderGlow } from '../BorderGlow';
import { AuditReport, BrandDNAProfile } from '../../types/brandDna';
import { useKeyContext } from '../../context/KeyContext';

interface DiagnosticDashboardProps {
  report: AuditReport | null;
  isAuditing?: boolean;
  auditPhaseStep?: number;
  auditPhaseLabel?: string;
  onApplySuggestion: (original: string, replacement: string) => void;
}

export const DiagnosticDashboard: React.FC<DiagnosticDashboardProps> = ({
  report,
  isAuditing,
  auditPhaseStep = 1,
  auditPhaseLabel = '',
  onApplySuggestion
}) => {
  const { activeProfile } = useKeyContext();
  const [severityFilter, setSeverityFilter] = useState<'ALL' | 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'>('ALL');
  const [copiedExport, setCopiedExport] = useState(false);
  const [isWeightPanelOpen, setIsWeightPanelOpen] = useState(false);
  const [ruleWeights, setRuleWeights] = useState<Record<string, number>>(() => {
    const map: Record<string, number> = {};
    (activeProfile.rules || []).forEach((r) => {
      map[r.ruleId] = r.weight;
    });
    return map;
  });

  const handleSliderChange = (ruleId: string, value: number) => {
    setRuleWeights((prev) => ({ ...prev, [ruleId]: value }));
  };

  const generateMarkdownExport = (rep: AuditReport, dna: BrandDNAProfile): string => {
    const contextLine = rep.contentContext ? `**Content Context**: ${rep.contentContext}  \n` : '';
    const engineLine = (rep.usedModel || rep.semantic.usedModel)
      ? `**AI Engine**: ${rep.usedModel || rep.semantic.usedModel}${rep.fallbackNotice || rep.semantic.fallbackNotice ? ` (${rep.fallbackNotice || rep.semantic.fallbackNotice})` : ''}  \n`
      : '';
    return `# LoomFrog Brand DNA Audit Report
**Brand**: ${dna.metadata.brandName} (v${dna.metadata.brandVersion})  
**Date**: ${new Date(rep.timestamp).toLocaleString()}  
${engineLine}${contextLine}**Composite Alignment Score**: ${rep.scores.sOverall}% (${rep.scores.overallRatingLabel})  
**Confidence Index**: ${(rep.scores.confidenceIndex * 100).toFixed(0)}%

---

## 1. Executive Summary & Scores
- **Deterministic Vocabulary Score**: ${rep.scores.sDet}%
- **Semantic Tone Score**: ${rep.scores.sSem}%
- **Deterministic Violations Found**: ${rep.deterministic.textMatches.length}
- **Semantic Observations**: ${rep.semantic.observations.length}

---

## 2. Actionable Diagnostics & Suggested Alignments
${
  rep.semantic.observations.length === 0 && rep.deterministic.textMatches.length === 0
    ? '_No brand discrepancies detected. Full compliance achieved._'
    : rep.semantic.observations
        .map(
          (obs, idx) => `
### Finding #${idx + 1} [${obs.severity}] — Rule ${obs.ruleId}
- **Summary**: ${obs.findingSummary}
- **Detected Issue**: "${obs.evidenceQuote}"
- **Suggested Alignment**: "${obs.suggestedRewrite}"
- **Confidence**: ${(obs.confidence * 100).toFixed(0)}%
`
        )
        .join('\n')
}

---
_Generated by LoomFrog Zero-Server Brand DNA Guardian._
`;
  };

  const handleCopyMarkdown = () => {
    if (!report) return;
    const md = generateMarkdownExport(report, activeProfile);
    navigator.clipboard.writeText(md);
    setCopiedExport(true);
    setTimeout(() => {
      setCopiedExport(false);
    }, 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!report) return;
    const md = generateMarkdownExport(report, activeProfile);
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `LoomFrog-BrandAudit-${activeProfile.metadata.brandName}-${new Date().toISOString().slice(0, 10)}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Loading state during active audit
  if (isAuditing) {
    return (
      <BorderGlow borderRadius="rounded-3xl" glowColor="cyan" animated>
        <div className="p-8 rounded-3xl neo-liquid-panel space-y-6 text-center animate-fade-in">
          <div className="w-14 h-14 mx-auto rounded-2xl bg-gradient-to-br from-teal-500 to-cyan-500 flex items-center justify-center shadow-[0_0_30px_rgba(6,182,212,0.5)]">
            <RefreshCw className="w-7 h-7 text-white animate-spin" />
          </div>

          <div>
            <h3 className="text-lg font-bold text-white font-lexend">Evaluating Brand DNA Compliance</h3>
            <p className="text-xs text-cyan-300 mt-1 font-mono">{auditPhaseLabel || 'Executing dual-tier verification...'}</p>
          </div>

          {/* Multi-step progress bar */}
          <div className="max-w-md mx-auto space-y-2">
            <div className="flex justify-between text-[11px] font-mono text-slate-400">
              <span>Step {auditPhaseStep} of 4</span>
              <span>{auditPhaseStep === 1 ? 'Deterministic' : auditPhaseStep === 2 ? 'Canvas' : auditPhaseStep === 3 ? 'Semantic AI' : 'Scoring'}</span>
            </div>
            <div className="h-2 w-full bg-[#02050f] rounded-full overflow-hidden border border-cyan-500/20">
              <div
                className="h-full bg-gradient-to-r from-teal-400 via-cyan-400 to-blue-500 transition-all duration-300 shadow-[0_0_12px_rgba(34,211,238,0.8)]"
                style={{ width: `${(auditPhaseStep / 4) * 100}%` }}
              />
            </div>
          </div>
        </div>
      </BorderGlow>
    );
  }

  // If no report has been generated yet
  if (!report) {
    return (
      <BorderGlow borderRadius="rounded-3xl" glowColor="cyan">
        <div className="p-10 rounded-3xl neo-liquid-panel text-center space-y-4">
          <div className="w-14 h-14 mx-auto rounded-2xl bg-[#02050f] border border-cyan-500/20 flex items-center justify-center text-cyan-400 shadow-inner">
            <Sparkles className="w-7 h-7" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white font-lexend">Diagnostic Engine Standing By</h3>
          </div>
        </div>
      </BorderGlow>
    );
  }

  const { scores, deterministic, semantic } = report;
  const observations = semantic?.observations || [];

  // Filter observations based on severity
  const filteredObservations = observations.filter((obs) => {
    if (severityFilter === 'ALL') return true;
    return obs.severity === severityFilter;
  });

  const criticalCount = observations.filter((o) => o.severity === 'CRITICAL').length;
  const highCount = observations.filter((o) => o.severity === 'HIGH').length;
  const mediumCount = observations.filter((o) => o.severity === 'MEDIUM').length;
  const lowCount = observations.filter((o) => o.severity === 'LOW').length;

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Top Banner: Score Matrix & Visual Circular Gauges */}
      <BorderGlow
        borderRadius="rounded-3xl"
        glowColor={scores.sOverall >= 85 ? 'teal' : scores.sOverall >= 65 ? 'amber' : 'rose'}
        active={scores.sOverall >= 85}
      >
        <div className="p-6 sm:p-7 rounded-3xl neo-liquid-panel relative overflow-hidden space-y-6">
          {/* Main Overall Brand Alignment Score & Audit Verdict Header */}
        <div className="flex flex-col sm:flex-row items-center sm:items-center gap-5 sm:gap-6 text-center sm:text-left">
          <ScoreGauge
            score={scores.sOverall}
            label="Brand Alignment"
            mathSymbol="Alignment"
            description="Composite DNA Compliance"
            size="lg"
          />
          <div>
            <div className="flex items-center justify-center sm:justify-start gap-2">
              <span className="text-xs font-bold text-cyan-300 font-lexend uppercase tracking-wider">
                Audit Verdict
              </span>
              <span
                className={`text-[10px] px-2.5 py-0.5 rounded-full font-bold font-mono ${
                  scores.sOverall >= 85
                    ? 'bg-teal-950/60 text-teal-300 border border-teal-500/40'
                    : scores.sOverall >= 65
                    ? 'bg-amber-950/60 text-amber-300 border border-amber-500/40'
                    : 'bg-rose-950/60 text-rose-300 border border-rose-500/40'
                }`}
              >
                {scores.overallRatingLabel.replace('_', ' ')}
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white font-lexend mt-1.5">
              {activeProfile.metadata.brandName} Guidelines
            </h2>
            <p className="text-xs text-slate-400 mt-1 max-w-xl">
              Confidence Index: <strong className="text-cyan-300 font-mono">{(scores.confidenceIndex * 100).toFixed(0)}%</strong> &bull; Zero-server client isolation verified.
            </p>
            {report.contentContext && (
              <div className="mt-2 inline-flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-cyan-950/40 border border-cyan-500/20 text-xs text-cyan-200">
                <Sparkles className="w-3 h-3 text-cyan-400 shrink-0" />
                <span>Context: <strong className="text-slate-200 font-medium font-sans">&ldquo;{report.contentContext}&rdquo;</strong></span>
              </div>
            )}
          </div>
        </div>

        {/* Fallback Model Transparency Notice */}
        {(report.fallbackNotice || report.semantic?.fallbackNotice) && (
          <div className="p-3.5 rounded-2xl bg-gradient-to-r from-amber-950/60 via-[#040918] to-amber-950/40 border border-amber-500/40 text-xs text-amber-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-[0_0_20px_rgba(245,158,11,0.15)] animate-fade-in">
            <div className="flex items-center gap-2.5">
              <AlertCircle className="w-4 h-4 text-amber-400 shrink-0" />
              <span className="leading-relaxed font-medium">
                {report.fallbackNotice || report.semantic?.fallbackNotice}
              </span>
            </div>
            <span className="text-[10px] font-mono px-2.5 py-0.5 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/30 font-semibold shrink-0 self-start sm:self-auto">
              Fallback Model Used
            </span>
          </div>
        )}

        {/* Sub-Score Gauges Grid (Tone, Precision, Clarity in row below) */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5 sm:gap-4">
          <ScoreGauge
            score={scores.sSem}
            label="Tone"
            mathSymbol="Tone"
            description="Voice & formality alignment"
            size="md"
          />
          <ScoreGauge
            score={scores.sDet}
            label="Precision"
            mathSymbol="Precision"
            description="Vocabulary & rule accuracy"
            size="md"
          />
          <ScoreGauge
            score={
              deterministic.colorClusters && deterministic.colorClusters.length > 0
                ? Math.round(deterministic.score)
                : Math.round(scores.sDet * 0.4 + scores.sSem * 0.6)
            }
            label="Clarity"
            mathSymbol="Clarity"
            description={
              deterministic.colorClusters && deterministic.colorClusters.length > 0
                ? 'Visual & palette harmony'
                : 'Message flow & readability'
            }
            size="md"
          />
        </div>

        {/* Statistical Summary Ribbon */}
        <div className="pt-4 border-t border-cyan-500/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs">
          <div className="flex flex-wrap items-center gap-3 sm:gap-4 text-slate-300">
            <div>
              <span className="text-slate-400">Total Findings:</span>{' '}
              <strong className="text-white font-mono">{observations.length}</strong>
            </div>
            <div>
              <span className="text-rose-400">Critical:</span>{' '}
              <strong className="text-rose-300 font-mono">{criticalCount}</strong>
            </div>
            <div>
              <span className="text-amber-400">Medium/High:</span>{' '}
              <strong className="text-amber-300 font-mono">{highCount + mediumCount}</strong>
            </div>
            <div>
              <span className="text-cyan-400">Low:</span>{' '}
              <strong className="text-cyan-300 font-mono">{lowCount}</strong>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto">
            {/* Weight Calibration Toggle */}
            <button
              onClick={() => setIsWeightPanelOpen(!isWeightPanelOpen)}
              className="inline-flex items-center gap-1 px-3 py-1.5 rounded-xl bg-[#02050f]/80 text-cyan-300 hover:text-white border border-cyan-500/20 text-xs font-medium cursor-pointer transition-all shadow-sm shrink-0"
            >
              <Sliders className="w-3.5 h-3.5" />
              Calibrate Weights
              <ChevronDown className={`w-3.5 h-3.5 transition-transform ${isWeightPanelOpen ? 'rotate-180' : ''}`} />
            </button>

            {/* Markdown Export Options */}
            <button
              onClick={handleCopyMarkdown}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#02050f]/80 text-slate-300 hover:text-white border border-cyan-500/20 text-xs font-medium cursor-pointer transition-all shadow-sm shrink-0"
            >
              {copiedExport ? <CheckCircle2 className="w-3.5 h-3.5 text-teal-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedExport ? 'Copied MD!' : 'Copy Markdown'}
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#02050f]/80 text-teal-300 hover:text-teal-200 border border-teal-500/30 text-xs font-semibold cursor-pointer transition-all shadow-sm shrink-0"
            >
              <Download className="w-3.5 h-3.5" />
              Download Report
            </button>
          </div>
        </div>

        {/* Live Weight Sliders Panel */}
        {isWeightPanelOpen && (
          <div className="mt-4 p-4 rounded-2xl bg-[#02050f]/90 border border-cyan-500/30 text-xs space-y-3 animate-fade-in shadow-inner">
            <div className="flex items-center justify-between">
              <span className="font-bold text-cyan-200 font-lexend">
                Dynamic Rule Weighting &amp; Real-time Sensitivity
              </span>
              <span className="text-[11px] text-slate-400 font-mono">Formula: S_overall = (S_det * 0.4) + (S_sem * 0.6)</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
              {(activeProfile.rules || []).map((rule) => {
                const currentWeight = ruleWeights[rule.ruleId] ?? rule.weight;
                return (
                  <div key={rule.ruleId} className="p-2.5 rounded-xl bg-[#0c1626]/60 border border-cyan-500/10 space-y-1.5">
                    <div className="flex items-center justify-between text-[11px]">
                      <span className="font-mono text-cyan-300 font-bold">{rule.ruleId}</span>
                      <span className="text-slate-400">Weight: <strong className="text-white">{currentWeight.toFixed(1)}x</strong></span>
                    </div>
                    <p className="text-[10px] text-slate-300 line-clamp-1">{rule.description}</p>
                    <input
                      type="range"
                      min="0.5"
                      max="5.0"
                      step="0.5"
                      value={currentWeight}
                      onChange={(e) => handleSliderChange(rule.ruleId, parseFloat(e.target.value))}
                      className="w-full accent-cyan-400 cursor-pointer h-1.5 bg-slate-800 rounded-lg"
                    />
                  </div>
                );
              })}
            </div>
          </div>
        )}
        </div>
      </BorderGlow>

      {/* Findings Section */}
      <div className="space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <h3 className="text-base font-bold text-white font-lexend">
              Actionable Diagnostics &amp; Alignment Diffs
            </h3>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-cyan-950/60 text-cyan-300 border border-cyan-500/30 font-mono">
              {filteredObservations.length}
            </span>
          </div>

          {/* Severity Filters */}
          <div className="flex items-center gap-1 sm:gap-1.5 bg-[#02050f]/80 p-1 rounded-2xl border border-cyan-500/20 overflow-x-auto no-scrollbar max-w-full">
            {(['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const).map((sev) => (
              <button
                key={sev}
                onClick={() => setSeverityFilter(sev)}
                className={`px-2.5 sm:px-3 py-1 rounded-xl text-xs font-semibold transition-all cursor-pointer shrink-0 ${
                  severityFilter === sev
                    ? 'bg-cyan-500/30 text-white border border-cyan-400/50 shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {sev}
              </button>
            ))}
          </div>
        </div>

        {/* List of Diff Cards */}
        {filteredObservations.length === 0 ? (
          <BorderGlow borderRadius="rounded-3xl" glowColor="teal">
            <div className="p-8 rounded-3xl neo-liquid-panel text-center space-y-2">
              <FileCheck className="w-10 h-10 text-teal-400 mx-auto" />
              <h4 className="text-base font-bold text-white font-lexend">Perfect Brand Alignment</h4>
              <p className="text-xs text-slate-400 max-w-md mx-auto">
                No brand discrepancies found for this filter level. Your draft complies with all configured Brand DNA guidelines.
              </p>
            </div>
          </BorderGlow>
        ) : (
          <div className="space-y-3">
            {filteredObservations.map((obs, idx) => (
              <DiffCard
                key={`obs-${obs.ruleId}-${idx}`}
                ruleId={obs.ruleId}
                severity={obs.severity}
                confidence={obs.confidence}
                evidenceQuote={obs.evidenceQuote}
                findingSummary={obs.findingSummary}
                suggestedRewrite={obs.suggestedRewrite}
                onApplyRewrite={onApplySuggestion}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
